### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by miliardopiscrat** [silversonicaxel/gherkin-detailer#6]
npm install -g gherkin-detailer

npm ERR! gherkin-detailer@1.2.0 prepare-dist: `mkdir -p dist/templates; cp src/templates/* dist/templates`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gherkin-detailer@1.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by silversonicaxel** [comment]
Can you tell me more? This is what I see from my  #console:

➜  ~ npm install -g gherkin-detailer

/..../.nvm/versions/node/v10.15.2/bin/gherkin-detailer -> /..../.nvm/versions/node/v10.15.2/lib/node_modules/gherkin-detailer/dist/index.js

> gherkin-detailer@1.2.0 postinstall /..../.nvm/versions/node/v10.15.2/lib/node_modules/gherkin-detailer
> npm run prepare-dist


> gherkin-detailer@1.2.0 prepare-dist /..../.nvm/versions/node/v10.15.2/lib/node_modules/gherkin-detailer
> mkdir -p dist/templates; cp src/templates/* dist/templates

+ gherkin-detailer@1.2.0
added 36 packages from 60 contributors in 5.274s`

Thanks a lot

**Comment by miliardopiscrat** [comment]
mkdir -p dist/templates; cp src/templates/* dist/templates
The syntax of the command is incorrect, probably system dependant.

**Comment by silversonicaxel** [comment]
Which operating system are you using? Can you give me more details, thanks? 
Nevertheless I will check it.

**Comment by miliardopiscrat** [comment]
windows10 with cmd tool from https://git-scm.com/download/win

**Comment by miliardopiscrat** [comment]
https://stackoverflow.com/questions/39727920/cant-use-mkdir-in-npm-script-from-windows

**Comment by silversonicaxel** [comment]
Honestly I didn't develop this app thinking about Windows. Feel free to fork it and develop something compatible.
